import { Category, Currency, SubCategory} from "~/types";
import { combineCategoriesWithProducts } from "./combineCategoriesWithProducts";
import { category_kk } from "./category_kk";
import type { IProduct } from "~/types";

const data: IProduct[] = [
    {
        id: 1,
        slug: 'iphone-14-pro',
        preview_image: ['/products/iphone-14-pro-front.jpg', '/products/iphone-14-pro-back.jpg', '/products/iphone-14-pro-side.jpg'],
        category: Category.SMARTPHONES,
        sub_category: SubCategory.SMARTPHONES_IOS,
        images: ['/products/iphone-14-pro-front.jpg', '/products/iphone-14-pro-back.jpg', '/products/iphone-14-pro-side.jpg'],
        title: 'iPhone 14 Pro',
        price: 1199,
        currency: Currency.USD,
        rates: 4.8,
        count_rates: 1523,
        is_stock: true,
        delivery: true,
        delivery_time: '3-5 күндер'
    },
    {
        id: 2,
        slug: 'macbook-pro-16',
        preview_image: ['/products/macbook-pro-front.webp', '/products/macbook-pro-back.jpeg', '/products/macbook-pro-side.jpg'],
        category: Category.LAPTOPS,
        sub_category: SubCategory.LAPTOPS_BUSINESS,
        images: ['/products/macbook-pro-front.webp', '/products/macbook-pro-back.jpeg', '/products/macbook-pro-side.jpg'],
        title: 'MacBook Pro 16"',
        price: 2499,
        currency: Currency.USD,
        rates: 4.9,
        count_rates: 1032,
        is_stock: true,
        delivery: true,
        delivery_time: '1-3 күндер'
    },
    {
        id: 3,
        slug: 'samsung-galaxy-tab-s9',
        preview_image: ['/products/tab-s9-front.webp', '/products/tab-s9-back.jpg', '/products/tab-s9-side.jpg'],
        category: Category.TABLETS,
        sub_category: SubCategory.SMARTPHONES_ANDROID, // Пример использования универсальной подкатегории
        images: ['/products/tab-s9-front.webp', '/products/tab-s9-back.jpg', '/products/tab-s9-side.jpg'],
        title: 'Samsung Galaxy Tab S9',
        price: 799,
        currency: Currency.USD,
        rates: 4.7,
        count_rates: 834,
        is_stock: true,
        delivery: true,
        delivery_time: '3-5 күндер'
    },
    {
        id: 4,
        slug: 'sony-bravia-x95j',
        preview_image: ['/products/sony.webp', '/products/sony-2.jpg', '/products/sony-3.jpg'],
        category: Category.TELEVISIONS,
        sub_category: SubCategory.TELEVISIONS_OLED,
        images: ['/products/sony.webp', '/products/sony-2.jpg', '/products/sony-3.jpg'],
        title: 'Sony Bravia X95J 75"',
        price: 2299,
        currency: Currency.USD,
        rates: 4.8,
        count_rates: 1231,
        is_stock: true,
        delivery: true,
        delivery_time: '5-7 күндер'
    },
    {
        id: 5,
        slug: 'bose-quietcomfort-45',
        preview_image: ['/products/bose-1.webp', '/products/bose-2.webp', '/products/bose-3.webp'],
        category: Category.HEADPHONES,
        sub_category: SubCategory.ACCESSORIES_KEYBOARDS, // Пример, если отсутствует явная сабкатегория
        images: ['/products/bose-1.webp', '/products/bose-2.webp', '/products/bose-3.webp'],
        title: 'Bose QuietComfort 45',
        price: 329,
        currency: Currency.USD,
        rates: 4.6,
        count_rates: 945,
        is_stock: true,
        delivery: true,
        delivery_time: '3-5 күндер'
    },
    {
        id: 6,
        slug: 'canon-eos-r6',
        preview_image: ['/products/canon-3.jpg', '/products/canon-1.webp', '/products/canon-2.webp'],
        category: Category.CAMERAS,
        sub_category: SubCategory.CAMERAS_MIRRORLESS,
        images: ['/products/canon-3.jpg', '/products/canon-1.webp', '/products/canon-2.webp'],
        title: 'Canon EOS R6',
        price: 2499,
        currency: Currency.USD,
        rates: 4.7,
        count_rates: 732,
        is_stock: true,
        delivery: true,
        delivery_time: '5-7 күндер'
    },
    {
        id: 7,
        slug: 'playstation-5',
        preview_image: ['/products/ps5-1.jpg', '/products/ps5-2.webp', '/products/ps5-3.webp'],
        category: Category.GAMING_CONSOLES,
        sub_category: SubCategory.GAMING_CONSOLES_HOME,
        images: ['/products/ps5-1.jpg', '/products/ps5-2.webp', '/products/ps5-3.webp'],
        title: 'Sony PlayStation 5',
        price: 499,
        currency: Currency.USD,
        rates: 4.9,
        count_rates: 1543,
        is_stock: true,
        delivery: true,
        delivery_time: '2-4 күндер'
    },
    {
        id: 8,
        slug: 'dyson-v15-detect',
        preview_image: ['/products/dyson-1.jpg', '/products/dyson-2.webp', '/products/dyson-3.webp'],
        category: Category.HOME_APPLIANCES,
        sub_category: SubCategory.HOME_APPLIANCES_VACUUMS,
        images: ['/products/dyson-1.jpg', '/products/dyson-2.webp', '/products/dyson-3.webp'],
        title: 'Dyson V15 Detect Vacuum',
        price: 749,
        currency: Currency.USD,
        rates: 4.8,
        count_rates: 623,
        is_stock: true,
        delivery: true,
        delivery_time: '3-5 күндер'
    },
    {
        id: 9,
        slug: 'google-nest-thermostat',
        preview_image: ['/products/nest-thermostat-1.webp', '/products/nest-thermostat-2.webp', '/products/nest-thermostat-3.webp'],
        category: Category.SMART_HOME_DEVICES,
        sub_category: SubCategory.SMART_HOME_CONTROLS,
        images: ['/products/nest-thermostat-1.webp', '/products/nest-thermostat-2.webp', '/products/nest-thermostat-3.webp'],
        title: 'Google Nest Thermostat',
        price: 129,
        currency: Currency.USD,
        rates: 4.5,
        count_rates: 412,
        is_stock: true,
        delivery: true,
        delivery_time: '3-5 күндер'
    },
    {
        id: 10,
        slug: 'apple-watch-series-9',
        preview_image: ['/products/apple-watch-1.webp', '/products/apple-watch-2.webp', '/products/apple-watch-3.webp'],
        category: Category.WEARABLES,
        sub_category: SubCategory.WEARABLES_SMARTWATCHES,
        images: ['/products/apple-watch-1.webp', '/products/apple-watch-2.webp', '/products/apple-watch-3.webp'],
        title: 'Apple Watch Series 9',
        price: 399,
        currency: Currency.USD,
        rates: 4.7,
        count_rates: 1223,
        is_stock: true,
        delivery: true,
        delivery_time: '1-3 күндер'
    },
    {
        id: 11,
        slug: 'anker-powercore-20000',
        preview_image: ['/products/anker-powerbank-1.jpg', '/products/anker-powerbank-2.webp', '/products/anker-powerbank-3.png'],
        category: Category.ACCESSORIES,
        sub_category: SubCategory.ACCESSORIES_POWERBANKS,
        images: ['/products/anker-powerbank-1.jpg', '/products/anker-powerbank-2.webp', '/products/anker-powerbank-3.png'],
        title: 'Anker PowerCore 20000mAh',
        price: 49,
        currency: Currency.USD,
        rates: 4.8,
        count_rates: 834,
        is_stock: true,
        delivery: true,
        delivery_time: '3-5 күндер'
    },
    {
        id: 12,
        slug: 'hp-laserjet-pro',
        preview_image: ['/products/hp-printer-1.webp', '/products/hp-printer-2.jpg', '/products/hp-printer-3.webp'],
        category: Category.PRINTERS,
        sub_category: null, // У этой категории нет выделенной сабкатегории
        images: ['/products/hp-printer-1.webp', '/products/hp-printer-2.jpg', '/products/hp-printer-3.webp'],
        title: 'HP LaserJet Pro',
        price: 199,
        currency: Currency.USD,
        rates: 4.6,
        count_rates: 512,
        is_stock: true,
        delivery: true,
        delivery_time: '3-5 күндер'
    },
    {
        id: 13,
        slug: 'lg-ultragear-32gn650',
        preview_image: ['/products/lg-monitor-1.webp', '/products/lg-monitor-2.jpg', '/products/lg-monitor-3.webp'],
        category: Category.MONITORS,
        sub_category: SubCategory.MONITORS_GAMING,
        images: ['/products/lg-monitor-1.webp', '/products/lg-monitor-2.jpg', '/products/lg-monitor-3.webp'],
        title: 'LG UltraGear 32" 165Hz Monitor',
        price: 399,
        currency: Currency.USD,
        rates: 4.8,
        count_rates: 923,
        is_stock: true,
        delivery: true,
        delivery_time: '3-5 күндер'
    },
    {
        id: 14,
        slug: 'tp-link-archer-ax73',
        preview_image: ['/products/tp-link-router-1.webp', '/products/tp-link-router-2.webp'],
        category: Category.NETWORKING_DEVICES,
        sub_category: null, // Нет выделенной сабкатегории
        images: ['/products/tp-link-router-1.webp', '/products/tp-link-router-2.webp'],
        title: 'TP-Link Archer AX73 Wi-Fi 6 Router',
        price: 179,
        currency: Currency.USD,
        rates: 4.7,
        count_rates: 611,
        is_stock: true,
        delivery: true,
        delivery_time: '2-4 күндер'
    },
    {
        id: 15,
        slug: 'samsung-t7-1tb',
        preview_image: ['/products/samsung-t7-1.webp'],
        category: Category.STORAGE_DEVICES,
        sub_category: SubCategory.STORAGE_DEVICES_EXTERNAL,
        images: ['/products/samsung-t7-1.webp', '/products/samsung-t7-2.jpg'],
        title: 'Samsung T7 Portable SSD 1TB',
        price: 119,
        currency: Currency.USD,
        rates: 4.9,
        count_rates: 1023,
        is_stock: true,
        delivery: true,
        delivery_time: '3-5 күндер'
    },
    {
        id: 16,
        slug: 'nintendo-switch-oled',
        preview_image: ['/products/switch-oled-1.jpg'],
        category: Category.GAMING_CONSOLES,
        sub_category: SubCategory.GAMING_CONSOLES_HANDHELD,
        images: ['/products/switch-oled-1.jpg'],
        title: 'Nintendo Switch OLED',
        price: 349,
        currency: Currency.USD,
        rates: 4.8,
        count_rates: 1450,
        is_stock: true,
        delivery: true,
        delivery_time: '2-4 күндер'
    },
    {
        id: 17,
        slug: 'sony-wh-1000xm5',
        preview_image: ['/products/sony-xm5-1.webp', '/products/sony-xm5-2.png'],
        category: Category.HEADPHONES,
        sub_category: null, // Нет выделенной сабкатегории
        images: ['/products/sony-xm5-1.webp', '/products/sony-xm5-2.png'],
        title: 'Sony WH-1000XM5',
        price: 399,
        currency: Currency.USD,
        rates: 4.9,
        count_rates: 1630,
        is_stock: true,
        delivery: true,
        delivery_time: '3-5 күндер'
    },
    {
        id: 18,
        slug: 'samsung-qled-q90',
        preview_image: ['/products/samsung-qled-1.webp'],
        category: Category.TELEVISIONS,
        sub_category: SubCategory.TELEVISIONS_OLED,
        images: ['/products/samsung-qled-1.webp', '/products/samsung-qled-2.jpg'],
        title: 'Samsung QLED Q90 65"',
        price: 1999,
        currency: Currency.USD,
        rates: 4.8,
        count_rates: 920,
        is_stock: true,
        delivery: true,
        delivery_time: '5-7 күндер'
    },
    {
        id: 19,
        slug: 'philips-hue-starter-kit',
        preview_image: ['/products/hue-kit-1.webp'],
        category: Category.SMART_HOME_DEVICES,
        sub_category: SubCategory.SMART_HOME_LIGHTING,
        images: ['/products/hue-kit-1.webp'],
        title: 'Philips Hue Starter Kit',
        price: 199,
        currency: Currency.USD,
        rates: 4.6,
        count_rates: 642,
        is_stock: true,
        delivery: true,
        delivery_time: '3-5 күндер'
    },
    {
        id: 20,
        slug: 'roborock-s8-pro',
        preview_image: ['/products/roborock-s8-1.webp'],
        category: Category.HOME_APPLIANCES,
        sub_category: SubCategory.HOME_APPLIANCES_VACUUMS,
        images: ['/products/roborock-s8-1.webp', '/products/roborock-s8-2.webp'],
        title: 'Roborock S8 Pro Robot Vacuum',
        price: 799,
        currency: Currency.USD,
        rates: 4.7,
        count_rates: 732,
        is_stock: true,
        delivery: true,
        delivery_time: '5-7 күндер'
    },
    {
        id: 21,
        slug: 'lenovo-thinkpad-x1',
        preview_image: ['/products/thinkpad-x1-1.jpg'],
        category: Category.LAPTOPS,
        sub_category: SubCategory.LAPTOPS_BUSINESS,
        images: ['/products/thinkpad-x1-1.jpg'],
        title: 'Lenovo ThinkPad X1 Carbon',
        price: 1599,
        currency: Currency.USD,
        rates: 4.8,
        count_rates: 620,
        is_stock: true,
        delivery: true,
        delivery_time: '3-5 күндер'
    },
    {
        id: 22,
        slug: 'logitech-mx-master-3s',
        preview_image: ['/products/mx-master-1.webp'],
        category: Category.ACCESSORIES,
        sub_category: SubCategory.ACCESSORIES_MICE,
        images: ['/products/mx-master-1.webp'],
        title: 'Logitech MX Master 3S',
        price: 99,
        currency: Currency.USD,
        rates: 4.9,
        count_rates: 1500,
        is_stock: true,
        delivery: true,
        delivery_time: '1-3 күндер'
    },
    {
        id: 23,
        slug: 'seagate-exos-x18',
        preview_image: ['/products/exos-x18-1.webp'],
        category: Category.STORAGE_DEVICES,
        sub_category: SubCategory.STORAGE_DEVICES_INTERNAL,
        images: ['/products/exos-x18-1.webp'],
        title: 'Seagate Exos X18 18TB',
        price: 499,
        currency: Currency.USD,
        rates: 4.7,
        count_rates: 452,
        is_stock: true,
        delivery: true,
        delivery_time: '3-5 күндер'
    },
    {
        id: 24,
        slug: 'asus-rog-strix-3080',
        preview_image: ['/products/rog-3080-1.webp', '/products/rog-3080-2.jpg'],
        category: Category.ACCESSORIES,
        sub_category: SubCategory.ACCESSORIES_KEYBOARDS, // Можно заменить на специализированную подкатегорию
        images: ['/products/rog-3080-1.webp', '/products/rog-3080-2.jpg'],
        title: 'ASUS ROG Strix GeForce RTX 3080',
        price: 1299,
        currency: Currency.USD,
        rates: 4.8,
        count_rates: 732,
        is_stock: true,
        delivery: true,
        delivery_time: '3-5 күндер'
    },
    {
        id: 25,
        slug: 'microsoft-surface-pro-9',
        preview_image: ['/products/surface-pro-1.jpg'],
        category: Category.TABLETS,
        sub_category: SubCategory.SMARTPHONES_ANDROID, // Подкатегорию можно заменить, если появится специализированная
        images: ['/products/surface-pro-1.jpg'],
        title: 'Microsoft Surface Pro 9',
        price: 1299,
        currency: Currency.USD,
        rates: 4.8,
        count_rates: 812,
        is_stock: true,
        delivery: true,
        delivery_time: '3-5 күндер'
    },
    {
        id: 26,
        slug: 'razer-blade-16',
        preview_image: ['/products/razer-blade-1.webp', '/products/razer-blade-2.jpg'],
        category: Category.LAPTOPS,
        sub_category: SubCategory.LAPTOPS_GAMING,
        images: ['/products/razer-blade-1.webp', '/products/razer-blade-2.jpg'],
        title: 'Razer Blade 16',
        price: 3499,
        currency: Currency.USD,
        rates: 4.9,
        count_rates: 450,
        is_stock: true,
        delivery: true,
        delivery_time: '3-5 күндер'
    },
    {
        id: 27,
        slug: 'fitbit-charge-6',
        preview_image: ['/products/fitbit-1.webp', '/products/fitbit-2.jpg'],
        category: Category.WEARABLES,
        sub_category: SubCategory.WEARABLES_FITNESS_TRACKERS,
        images: ['/products/fitbit-1.webp', '/products/fitbit-2.jpg'],
        title: 'Fitbit Charge 6',
        price: 179,
        currency: Currency.USD,
        rates: 4.6,
        count_rates: 1021,
        is_stock: true,
        delivery: true,
        delivery_time: '3-5 күндер'
    },
    {
        id: 28,
        slug: 'lg-c2-oled-55',
        preview_image: ['/products/lg-c2-1.webp'],
        category: Category.TELEVISIONS,
        sub_category: SubCategory.TELEVISIONS_OLED,
        images: ['/products/lg-c2-1.webp'],
        title: 'LG C2 OLED 55"',
        price: 1799,
        currency: Currency.USD,
        rates: 4.9,
        count_rates: 920,
        is_stock: true,
        delivery: true,
        delivery_time: '3-5 күндер'
    },
    {
        id: 29,
        slug: 'gopro-hero-12',
        preview_image: ['/products/gopro-hero-1.webp'],
        category: Category.CAMERAS,
        sub_category: SubCategory.CAMERAS_ACTION,
        images: ['/products/gopro-hero-1.webp'],
        title: 'GoPro HERO 12',
        price: 399,
        currency: Currency.USD,
        rates: 4.8,
        count_rates: 1420,
        is_stock: true,
        delivery: true,
        delivery_time: '3-5 күндер'
    },
    {
        id: 30,
        slug: 'dyson-pure-cool',
        preview_image: ['/products/dyson-pure-cool-1.webp'],
        category: Category.HOME_APPLIANCES,
        sub_category: SubCategory.HOME_APPLIANCES_VACUUMS, // Подкатегорию можно заменить, если есть более точная
        images: ['/products/dyson-pure-cool-1.webp'],
        title: 'Dyson Pure Cool Air Purifier',
        price: 599,
        currency: Currency.USD,
        rates: 4.7,
        count_rates: 540,
        is_stock: true,
        delivery: true,
        delivery_time: '3-5 күндер'
    }
];

export const product_kk: IProduct[] = combineCategoriesWithProducts(
    category_kk,
    data
);
